### ISSUE TITLE
WynnBuilder is a fork of hppeng-wynn

### ISSUE THREAD

**Issue by xamionex** [pozgerab/WynnBuild#2]
[wynnbuilder.github.io](https://github.com/wynnbuilder/wynnbuilder.github.io) outdated by 5 months
[hppeng-wynn.github.io](https://github.com/hppeng-wynn/hppeng-wynn.github.io) being worked on constantly

**Comment by pozgerab** [comment]
Thanks for pointing this out, it will be changed in the next update!
