### ISSUE TITLE
Game Crashing when Creating build

### ISSUE THREAD

**Issue by Zepuuu** [pozgerab/WynnBuild#7]
When I try to create my build while I hold my Weapon in hand the game crashes. I Read the Ability tree and stats from my profile before. To finish the build I equipped my Weapon and pressed BUILD, then a "Saving world" screen appeared and the game closed

**Comment by pozgerab** [comment]
Please send the logs of the error

**Comment by Zepuuu** [comment]
[crash-2024-10-01_09.18.09-client.txt](https://github.com/user-attachments/files/17201050/crash-2024-10-01_09.18.09-client.txt)

**Comment by pozgerab** [comment]
Can you take a screenshot of the item in your main hand?

**Comment by Zepuuu** [comment]
![2024-10-04_14 40 29](https://github.com/user-attachments/assets/8867ccb4-597e-4e14-934f-fd5b20076bff)
this is my current weapon, but it still crashes

**Comment by pozgerab** [comment]
Thanks for the report, should be fixed in the latest update v0.4.4.1
