### ISSUE TITLE
Build button crashed game

### ISSUE THREAD

**Issue by BovineGoddes** [pozgerab/WynnBuild#8]
megawrzuta.pl/wymqdzuu - its a movie 

![image2](https://github.com/user-attachments/assets/9d8f683d-e9db-4628-9295-dd79bac90f63)
![image](https://github.com/user-attachments/assets/f758a5a8-fcea-432b-8981-0217c9ac09b4)
[crash-2024-10-27_22.08.24-client.txt](https://github.com/user-attachments/files/17535444/crash-2024-10-27_22.08.24-client.txt)

**Comment by pozgerab** [comment]
Can you send a screenshot of your inventory with the build that caused the crash?

**Comment by BovineGoddes** [comment]
I can send u full build 
https://wynnbuilder.github.io/builder/#9_CR-18r679e6b9e9e9g910KF0PW0Qz0JfCR-19i9k9i9k9H9x9m91CR-19i9k9i9k9H9x9c910uH0uz1t1Q-Y-Y1B1g1000361000361000361001Z61001Z61B1B0J0J0J0J0h1Tz-Itltie1

**Comment by pozgerab** [comment]
Please send a screenshot of your inventory too

**Comment by BovineGoddes** [comment]
![epoch 1](https://github.com/user-attachments/assets/db52aa7a-2bc1-41e5-bef0-6118a32e194b)
![epoch2](https://github.com/user-attachments/assets/0e68e268-8dab-4372-ab71-8ee0592f526f)

![epoch3](https://github.com/user-attachments/assets/973d754c-6315-4256-83fa-fe6c55908dce)
![epoch 4](https://github.com/user-attachments/assets/07d0c479-ba56-4705-95b3-cdb72e083e67)
![epoch5](https://github.com/user-attachments/assets/90e41c77-c87a-4c01-b955-afe1abf54ecb)
![epoch6](https://github.com/user-attachments/assets/204186fc-2c0d-4868-ba56-e231318e89e4)
![epoch7](https://github.com/user-attachments/assets/38f595e2-7455-4ed0-8a20-243c6df0244d)
![epoch8](https://github.com/user-attachments/assets/79550455-d43b-433a-a4cd-0206781ab1c7)
![eq](https://github.com/user-attachments/assets/e24f167b-ea08-4f35-a6a4-aee25ff2d8e0)

**Comment by pozgerab** [comment]
Thanks, I will look into the bug soon.

**Comment by pozgerab** [comment]
Should be fixed in the latest update 0.4.4.2, but I wont close the issue until you reply in case yours is a specific case. https://modrinth.com/mod/wynnbuild/version/v0.4.4.2+1.21
